JobWindowNew.Web/Controllers/BoardManagementController.cs
using JobWindowNew.Domain;
using JobWindowNew.Domain.ViewModels;
using JobWindowNew.Domain.ViewModels.Factories;
using System.Linq;
using System.Web.Mvc;

namespace JobWindowNew.Web.Controllers
{
    public class BoardManagementController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BoardManagementController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Index()
        {
            var query = _unitOfWork.JobBoardRepository
                .GetJobBoards().AsQueryable();

            var result = query.ToList()
                .Select(j => JobBoardFactory.Create(j, ""));

            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Create()
        {
            ;
            return View("BoardManagementForm",
                new JobBoardViewModel { Action = "Create" });
        }

        [HttpPost]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Create(JobBoardViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("BoardManagementForm", viewModel);

            var jobBoard = JobBoardFactory.Create(viewModel);

            _unitOfWork.JobBoardRepository.Add(jobBoard);

            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Edit(int id)
        {
            var jobBoard = _unitOfWork.JobBoardRepository.GetJobBoard(id);

            return View("BoardManagementForm",
                JobBoardFactory.Create(jobBoard, "Edit"));
        }

        [HttpPost]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Edit(JobBoardViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("BoardManagementForm", viewModel);

            var jobBoard = JobBoardFactory.Create(viewModel);

            _unitOfWork.JobBoardRepository.Update(jobBoard);

            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Root, Admin")]
        public ActionResult Delete(int id)
        {
            _unitOfWork.JobBoardRepository.Delete(id);

            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }
    }
}

JobWindowNew.Web/Controllers/JobsController.cs
using AutoMapper;
using JobWindowNew.DAL.Persistence.Helpers;
using JobWindowNew.Domain;
using JobWindowNew.Domain.Model;
using JobWindowNew.Domain.ViewModels;
using JobWindowNew.Web.Helpers;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace JobWindowNew.Web.Controllers
{
    public class JobsController : Controller
    {
        // GET: Jobs
        private readonly IUnitOfWork _unitOfWork;

        public JobsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize(Roles = "Root, Admin, Internal-Employee")]
        //[HttpGet]
        public ActionResult Index(string sortOrder, string idFilter, string titleFilter, string podIdFilter,
            string idSearch, string titleSearch,
            string cityFilter, string countryFilter, string categoryFilter, string stateFilter,
            string jobBoardFilter, string divisionFilter,
            string companyFilter, string statusSearch, string statusFilter,
            string citySearch, string countrySearch, string categorySearch, string stateSearch,
            string companySearch, string divisionSearch, string jobBoardSearch,
            string createdBySearch, string createdByFilter,
            string podIdSearch, int? page)
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.IdParm = sortOrder == "Id" ? "-Id" : "Id";
                ViewBag.CloneFromParm = sortOrder == "CloneFrom" ? "-CloneFrom" : "CloneFrom";
                ViewBag.EverGreenIdParm = sortOrder == "EverGreenId" ? "-EverGreenId" : "EverGreenId";
                ViewBag.TitleParm = sortOrder == "Title" ? "-Title" : "Title";
                ViewBag.JobBoardParm = sortOrder == "JobBoard.JobBoardName" ? "-JobBoard.JobBoardName" : "JobBoard.JobBoardName";
                ViewBag.CityParm = sortOrder == "City" ? "-City" : "City";
                ViewBag.StateNameParm = sortOrder == "State.StateName" ? "-State.StateName" : "State.StateName";
                ViewBag.CountryNameParm = sortOrder == "Country.CountryName" ? "-Country.CountryName" : "Country.CountryName";
                ViewBag.CategoryNameParm = sortOrder == "Category.CategoryName" ? "-Category.CategoryName" : "Category.CategoryName";
                ViewBag.CompanyNameParm = sortOrder == "CompanyName" ? "-CompanyName" : "CompanyName";
                ViewBag.SchedulingPodParm = sortOrder == "SchedulingPod" ? "-SchedulingPod" : "SchedulingPod";
                ViewBag.DivisionParm = sortOrder == "Division" ? "-Division" : "Division";
                ViewBag.ActivationDateParm = sortOrder == "ActivationDate" ? "-ActivationDate" : "ActivationDate";
                ViewBag.ExpirationDateParm = sortOrder == "ExpirationDate" ? "-ExpirationDate" : "ExpirationDate";
                ViewBag.CreatedByParm = sortOrder == "CreatedBy" ? "-CreatedBy" : "CreatedBy";
                ViewBag.CreatedDateParm = sortOrder == "CreatedDate" ? "-CreatedDate" : "CreatedDate";
                ViewBag.EmailParm = sortOrder == "EmailTo" ? "-EmailTo" : "EmailTo";
                ViewBag.OfficeParm = sortOrder == "OfficeId" ? "-OfficeId" : "OfficeId";
                ViewBag.BobParm = sortOrder == "Bob" ? "-Bob" : "Bob";
                ViewBag.IntvsParm = sortOrder == "Intvs" ? "-Intvs" : "Intvs";
                ViewBag.Intvs2Parm = sortOrder == "Intvs2" ? "-Intvs2" : "Intvs2";
                ViewBag.ApsClParm = sortOrder == "ApsCl" ? "-ApsCl" : "ApsCl";
                ViewBag.CreatedByParm = sortOrder == "CreatedBy" ? "-CreatedBy" : "CreatedBy";
                sortOrder = ViewBag.CurrentSort;

                if (idSearch != null || titleSearch != null || podIdSearch != null || citySearch != null ||
                    stateSearch != null || countrySearch != null || categorySearch != null || jobBoardSearch != null || companySearch != null ||
                    divisionSearch != null || statusSearch != null || createdBySearch != null)
                {
                    page = 1;
                }
                else
                {
                    idSearch = idFilter;
                    titleSearch = titleFilter;
                    podIdSearch = podIdFilter;
                    citySearch = cityFilter;
                    countrySearch = countryFilter;
                    categorySearch = categoryFilter;
                    stateSearch = stateFilter;
                    divisionSearch = divisionFilter;
                    companySearch = companyFilter;
                    jobBoardSearch = jobBoardFilter;
                    statusSearch = statusFilter;
                    createdBySearch = createdByFilter;
                }

                ViewBag.IdFilter = idSearch;
                ViewBag.TitleFilter = titleSearch;
                ViewBag.PodIdFilter = podIdSearch;
                ViewBag.CityFilter = citySearch;
                ViewBag.CountryFilter = countrySearch;
                ViewBag.CategoryFilter = categorySearch;
                ViewBag.StateFilter = stateSearch;
                ViewBag.DivisionFilter = divisionSearch;
                ViewBag.CompanyFilter = companySearch;
                ViewBag.JobBoardFilter = jobBoardSearch;
                ViewBag.StatusFilter = statusSearch;
                ViewBag.CreatedByFilter = createdBySearch;

                var query = _unitOfWork.JobRepository.GetJobs();

                query = PersistenceHelper.FilterByInput(idSearch, titleSearch, podIdSearch,
                    citySearch, stateSearch, countrySearch, categorySearch, jobBoardSearch,
                    divisionSearch, companySearch, statusSearch, createdBySearch, query);

                query = PersistenceHelper.SortForJobList(query);

                query = query.ApplySort(sortOrder);

                var mappedResult = query.Select(j => new JobGridViewModel
                {
                    Id = j.Id,
                    CloneFrom = j.CloneFrom,
                    EverGreenId = j.EverGreenId,
                    Title = j.Title,
                    TitleTruncated = j.Title.Substring(0, 20),
                    JobBoard = j.JobBoard.JobBoardName,
                    City = j.City,
                    StateName = j.State.StateName,
                    CountryName = j.Country.CountryCode,
                    CompanyName = j.CompanyName,
                    SchedulingPod = j.SchedulingPod,
                    Division = j.Division,
                    CreatedBy = j.CreatedBy,
                    CreatedByTruncated = j.CreatedBy.Substring(0, 10),
                    EmailTo = j.EmailTo,
                    EmailToTruncated = j.EmailTo.Substring(0, 10),
                    OfficeId = j.OfficeId,
                    Bob = j.Bob,
                    Intvs = j.Intvs,
                    Intvs2 = j.Intvs2,
                    ApsCl = j.ApsCl,
                    ActiveDate = j.ActivationDate,
                    ExpDate = j.ExpirationDate,
                    CreDate = j.CreatedDate,
                    IsExpired = j.ExpirationDate < DateTime.Now,
                    Category = j.Category.CategoryName,
                    IsOnlineApply = j.IsOnlineApply
                });

                var pageSize = 200;
                var pageNumber = (page ?? 1);

                var finalResult = mappedResult.ToPagedList(pageNumber, pageSize);
                foreach (var item in finalResult)
                {
                    item.ActivationDate = item.ActiveDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                    item.ExpirationDate = item.ExpDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                    item.CreatedDate = item.CreDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                    item.IsExpired = DateTime.Parse(item.ExpirationDate) < DateTime.Now;
                }

                return View(finalResult);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize(Roles = "Root, Admin, Internal-Employee")]
        //[HttpGet]
        public ActionResult Duplicates(string sortOrder, string idFilter, string titleFilter, string podIdFilter,
            string idSearch, string titleSearch,
            string cityFilter, string countryFilter, string stateFilter,
            string jobBoardFilter, string divisionFilter,
            string companyFilter,
            string citySearch, string countrySearch, string stateSearch,
            string companySearch, string divisionSearch, string jobBoardSearch,
            string podIdSearch, int? page)
        {
            try
            {
                ViewBag.CurrentSort = sortOrder;
                ViewBag.IdParm = sortOrder == "Id" ? "-Id" : "Id";
                ViewBag.CloneFromParm = sortOrder == "CloneFrom" ? "-CloneFrom" : "CloneFrom";
                ViewBag.EverGreenIdParm = sortOrder == "EverGreenId" ? "-EverGreenId" : "EverGreenId";
                ViewBag.TitleParm = sortOrder == "Title" ? "-Title" : "Title";
                ViewBag.JobBoardParm = sortOrder == "JobBoard.JobBoardName" ? "-JobBoard.JobBoardName" : "JobBoard.JobBoardName";
                ViewBag.CityParm = sortOrder == "City" ? "-City" : "City";
                ViewBag.StateNameParm = sortOrder == "State.StateName" ? "-State.StateName" : "State.StateName";
                ViewBag.CountryNameParm = sortOrder == "Country.CountryName" ? "-Country.CountryName" : "Country.CountryName";
                ViewBag.CompanyNameParm = sortOrder == "CompanyName" ? "-CompanyName" : "CompanyName";
                ViewBag.SchedulingPodParm = sortOrder == "SchedulingPod" ? "-SchedulingPod" : "SchedulingPod";
                ViewBag.DivisionParm = sortOrder == "Division" ? "-Division" : "Division";

JobWindowNew.Web/Controllers/StatsController.cs
using JobWindowNew.Domain;
using JobWindowNew.Domain.Model;
using JobWindowNew.Domain.ViewModels;
using PagedList;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace JobWindowNew.Web.Controllers
{
    public class StatsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public StatsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Stats
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [Authorize(Roles = "Root, Admin, Internal-Employee")]
        [HttpGet]
        public ActionResult Create(string podIdFilter, string podIdSearch, int? page)
        {

            if (podIdSearch != null)
            {
                page = 1;
            }
            else
            {
                podIdSearch = podIdFilter;
            }

            ViewBag.PodIdFilter = podIdSearch;

            IQueryable<Job> query;

            if (string.IsNullOrEmpty(podIdSearch))
            {
                query = _unitOfWork.JobRepository.GetJobsWithStats();
            }
            else
            {
                if (string.IsNullOrEmpty(podIdSearch))
                {
                    podIdSearch = "";
                }

                query = _unitOfWork.JobRepository.GetJobsWithStats()
                    .Where(j => j.SchedulingPod.ToString() == podIdSearch);
            }

            var mappedResult = query.Select(j => new JobStatsViewModel
            {
                Id = j.Id,
                Title = j.Title,
                TitleTruncated = j.Title.Substring(0, 20),
                SchedulingPod = j.SchedulingPod,
                JobBoard = j.JobBoard.JobBoardName,
                ApsCl = j.ApsCl,
                Intvs = j.Intvs,
                Intvs2 = j.Intvs2,
                Bob = j.Bob,
                ExpDate = j.ExpirationDate,
                ActiveDate = j.ActivationDate
            });

            var pageSize = 200;
            var pageNumber = (page ?? 1);

            var finalResult = mappedResult.ToPagedList(pageNumber, pageSize);
            foreach (var item in finalResult)
            {
                item.ActivationDate = item.ActiveDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                item.ExpirationDate = item.ExpDate.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            }

            return View(finalResult);
        }

        [Authorize(Roles = "Root, Admin, Internal-Employee")]
        [HttpPost]
        public ActionResult Create(IEnumerable<JobStatsViewModel> viewModel)
        {
            foreach (var vm in viewModel)
            {
                if (vm.Bob != null && vm.ApsCl != null && vm.Intvs != null
                    && vm.Intvs2 != null)
                {
                    var job = _unitOfWork.JobRepository.GetJob(vm.Id);
                    job.ApsCl = vm.ApsCl;
                    job.Intvs = vm.Intvs;
                    job.Intvs2 = vm.Intvs2;
                    job.Bob = vm.Bob;
                    job.HasStats = true;
                    _unitOfWork.JobRepository.Update(job);
                    _unitOfWork.Complete();
                }
            }

            return Redirect("Create");
        }
    }

}

JobWindowNew.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">
    var CKEDITOR_BASEPATH = '@Url.Content("~/Scripts/ckeditor/")';
    </script>    
    @Scripts.Render("~/bundles/ckeditorjs")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Job Window", "Index", "Jobs", new { area = "" }, new { @class = "navbar-brand" })
                @*<a aria-disabled="True" class="navbar-brand" href="#"><i class="glyphicon glyphicon-home"></i>  THE JOB WINDOW</a>*@
                @*<a aria-disabled="True" class="navbar-brand" href="#"><i class="glyphicon glyphicon-home"></i></a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown leftitems">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Listing Management<span class="caret"></span></a>
                        <ul class="dropdown-menu customeMenu">
                            <li class="leftitems">@Html.ActionLink("Job List", "Index", "Jobs")</li>
                            <li role="separator" class="divider"></li>                           
                            <li class="leftitems">@Html.ActionLink("Pending Stats", "Create", "Stats")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("Create", "Create", "Jobs")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("Mass Delete", "MassDelete", "Jobs")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("Mass Expire", "MassExpire", "Jobs")</li>
                        </ul>
                    </li>
                    <li class="dropdown leftitems">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports<span class="caret"></span></a>
                        <ul class="dropdown-menu customeMenu">
                            <li class="leftitems">@Html.ActionLink("EverGreen", "EverGreenReport", "Reports")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("Active", "ActiveReport", "Reports")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("In-Active", "InActiveReport", "Reports")</li>
                            <li role="separator" class="divider"></li>
                            <li class="leftitems">@Html.ActionLink("Created By", "CreatedByReport", "Reports")</li>
                        </ul>
                    </li>
@if (User.IsInRole("Root") || User.IsInRole("Admin"))
{
    <li class="dropdown leftitems">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Adminstration<span class="caret"></span></a>
        <ul class="dropdown-menu customeMenu">
            <li class="leftitems">@Html.ActionLink("Register", "Register", "Account")</li>
            <li role="separator" class="divider"></li>
            <li class="leftitems">@Html.ActionLink("Assign Role", "AssignRole", "Account")</li>
            <li role="separator" class="divider"></li>
            <li class="leftitems">@Html.ActionLink("View User Roles", "GetUsersWithRoles", "Account")</li>
            <li role="separator" class="divider"></li>
            <li class="leftitems">@Html.ActionLink("Board Management", "Index", "BoardManagement")</li>
        </ul>
    </li>
    <li class="leftitems">@Html.ActionLink("Applicants", "Index", "Applicants")</li>
}
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="font-size: small">
            <p>&copy; @DateTime.Now.Year - The Job Window</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/bootbox")
    @RenderSection("scripts", required: false)
</body>
</html>

JobWindowNew.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
    @Scripts.Render("~/bundles/ckeditorjs")

</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="font-size: small">
            <p>&copy; @DateTime.Now.Year - The Job Window</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>