JobWindowNew.Web/Controllers/ListController.cs
using AutoMapper;
using JobWindowNew.Domain;
using JobWindowNew.Domain.ViewModels;
using JobWindowNew.Domain.ViewModels.Factories;
using JobWindowNew.Web.Helpers;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace JobWindowNew.Web.Controllers
{
    public class ListController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ListController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var totalNumberOfJobs = _unitOfWork.JobRepository
                .GetJobs().Count();

            var info = PaginationInfoFactory.Create(totalNumberOfJobs);

            ViewBag.SortingPagingInfo = info;

            var query = _unitOfWork.JobRepository.GetJobsForList()
                .Take(info.PageSize).ToList();

            var result = Mapper.Map<IEnumerable<ImanJobs>>(query);

            return View(result);
        }

        [HttpPost]
        public ActionResult Index(PaginationInfoViewModel info)
        {
            var query = _unitOfWork.JobRepository.GetJobsForList();

            if (!string.IsNullOrEmpty(info.IdFilter))
            {
                query = query.Where(j => j.Id.ToString().Contains(info.IdFilter));
            }

            if (!string.IsNullOrEmpty(info.TitleFilter))
            {
                query = query.Where(j => j.Title.ToString().Contains(info.TitleFilter));
            }

            query = WebHelper.SortResult(info, query);

            info.TotalPages = WebHelper.GetNumberOfPages(info, query);

            ViewBag.SortingPagingInfo = info;

            var result = query.Skip(info.CurrentPage
                               * info.PageSize).Take(info.PageSize).ToList();

            return View(Mapper.Map<IEnumerable<ImanJobs>>(result));
        }


    }
}

JobWindowNew.Web/Views/List/Index.cshtml
@using JobWindowNew.Domain.ViewModels

@model IEnumerable<ImanJobs>

@{
    PaginationInfoViewModel info = ViewBag.SortingPagingInfo;
}

@{
    ViewBag.Title = "Index";
}

<h2>Job List</h2>
<div>
   
    @using (Html.BeginForm("Index", "List", FormMethod.Post))
    {   
        //@Html.Hidden("SortField", info.SortField)
        @Html.Hidden("SortDirection", info.SortDirection)
        @Html.Hidden("TotalPages", info.TotalPages)
        @Html.Hidden("PageSize", info.PageSize)
        @Html.Hidden("CurrentPage", info.CurrentPage)

        <table class="table table-hover" style="font-size: smaller">
            <thead>
            <tr>
                <th>
                    <a href="#" data-sortfield="Id"
                       class="header">@Html.DisplayNameFor(model => model.Id)</a>
                </th>
                <th>
                    <a href="#" data-sortfield="Title"
                       class="header">@Html.DisplayNameFor(model => model.Title)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StateName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CountryName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SchedulingPod)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Division)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobBoard)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsOnlineApply)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsExpired)
                </th>
            </tr>
            <tr>
                <th>@Html.TextBox("IdFilter", info.IdFilter)</th>
                <th>@Html.TextBox("TitleFilter", info.TitleFilter)</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StateName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CountryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SchedulingPod)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Division)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobBoard)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsOnlineApply)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsExpired)
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <input type="submit" hidden="hidden" onclick="$('#CurrentPage').val(0)"/>                   
        <div class="text-center">      
            <ul class="pagination pagination-sm">
            
                @{
                    if (0 == info.CurrentPage)
                    {
                        <li class="active"><a href="#">First Page</a></li>
                    }
                    else
                    {
                        <li>
                            <a href="#" data-pageindex=0
                               class="pager">First Page</a>
                        </li>
                    }

                    var start = 1;
                    if (info.CurrentPage - 5 > 0)
                    {
                        start = info.CurrentPage - 5;
                    }
                }
                @for (var i = start; i < info.TotalPages - 1 && i < info.CurrentPage + 5; i++)
                {
                    if (i == info.CurrentPage)
                    {
                        <li class="active"><a href="#">@(i + 1)</a></li>
                    }
                    else
                    {
                        <li>
                            <a href="#" data-pageindex="@i"
                               class="pager">@(i + 1)</a>
                        </li>
                    }
                }

                <li>
                    <a href="#" data-pageindex="@(info.TotalPages - 1)"
                       class="pager">Last Page</a>
                </li>
            </ul>
        </div>      
    }
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".header").click(function (evt) {
                $("#CurrentPage").val(0);                
                var sortfield = $(evt.target).data("sortfield");
                
                if ($("#SortField").val() === sortfield) {
                    if ($("#SortDirection").val() === "ascending") {
                        $("#SortDirection").val("descending");
                    }
                    else {
                        $("#SortDirection").val("ascending");
                    }
                }
                else {
                    $("#SortField").val(sortfield);
                    $("#SortDirection").val("ascending");
                }
                evt.preventDefault();
                $("form").submit();
            });

            $(".pager").click(function (evt) {
                var pageindex = $(evt.target).data("pageindex");
                $("#CurrentPage").val(pageindex);
                evt.preventDefault();
                $("form").submit();
            });
        });
    </script>
}